config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get 'home/about' => 'homes#about', as: 'about'
  
  devise_for :users
  
  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:index, :create, :show, :edit, :update, :destroy] do
    resources :book_comments, only: [:create]
  end 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  has_one_attached :profile_image
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resouce)
    about_path
  end
  
  def after_sign_out_path_for(resouce)
    root_path
  end
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end 
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end
  
  private
  
  def book_comment_params
    params.requier(:book_comments).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @book.save
    redirect_to books_path
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @user = current_user
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    book = Book.find(params[:id])
    book.update(book_params)
    redirect_to book_path(book.id)
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end 
  
  private
  
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to user_path(current_user)
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_index.html.erb
<table class="table">
  <thead>
    <tr>
      <th class="colspan-2"></th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
  </thead>
  
  <% books.each do |book| %>
  <tbody>
    <tr>
      <td>
        <%= image_tag book.user.get_profile_image(50,50) %>
      </td>
      <td>
        <%= link_to book_path(book.id) do %>
          <%= book.title %>
        <% end %>
      </td>
      <td><%= book.body %></td>
    </tr>
  </body>
  <% end %>
</table>

app/views/books/_new_book.html.erb
<%= form_with model:book do |f| %>
  <p>Title<br>
    <%= f.text_field :title %>
  </p>
  <p>Opinion<br>
    <%= f.text_area :body %><br>
  </p>
  <%= f.submit 'Create Book', class: "btn btn-success" %>
<% end %>

app/views/books/edit.html.erb
<div class="container pt-3">
  <div class="row">
    <div class="mx-auto">
      <h3>Editing Book</h3>
        <%= form_with model:@book do |f| %>
        
          <div class="book-title">
            <label for="inputTitle">Title</label><br>
            <%= f.text_field :title, autofocus:true, id:"inputTitle" %>
          </div>
          
          <div class="book-body">
            <label for="inputOpinion">Opinion</label><br>
            <%= f.text_field :body, id:"inputOpinion" %></br>
          </div>
          
          <div class="botton">
            <input class="btn btn-success" type="submit" value="Update Book">
          </div>
        <% end %>
          <%= link_to 'Show', book_path(@book.id) %>
          <a>|</a>
          <%= link_to 'back', books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2 class="mt-3">User info</h2>
        <%= render 'users/user_info', user: @user %>
      
      <h2>New Book</h2>
        <%= render 'new_book', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2 class="mt-3">Books</h2>
        <%= render 'index', books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2 class="mt-3">User info</h2>
        <%= render 'users/user_info', user: @user %>
      
      <h2 class="mt-3">New Book</h2>
        <%= render 'new_book', book: @book_new %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2 class="mt-3">Book detail</h2>
        <table>
          <tr>
            <th>
              <%= link_to user_path(@book.user_id) do %>
              <%= image_tag @book.user.get_profile_image(100,100) %></br>
              <%= @user.name %>
              <% end %>
            </th>
            <th><%= link_to @book.title, book_path(@book.id) %></th>
            <td><%= @book.body %></td>
            <% if @book.user == current_user %>
              <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-success" %></td>
              <td><%= link_to 'Destroy', book_path(@book), method: :delete, "data-confirm" => "本当に消しますか？", class: "btn btn-danger" %></td>
            <% end %>
          </tr>
        </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto mt-4">
      <h1>Welcome to
        <i class="fas fa-book"></i><strong>Bookers!</strong>
      </h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto mt-4">
      <h1>welcome to 
        <i class="fas fa-book"></i><strong>Bookers !!</strong>
      </h1>
      <p>
        In <i class="fas fa-book"></i><strong>Bookers,</strong><br>
      </p>
      </p>
        you can share and exhange your opinions, inpressions,and emotions<br>
      </p>
      <p>
        about carious books!
      </p>
      
      <div class="button">
        <%= link_to 'Log in', new_user_session_path, class: "btn btn-info btn-block mb-3" %>
        <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-success btn-block mb-3" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto mt-5">
      <p>CopyRight Infratop.inc</p>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                     aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li>
              <%= link_to user_path(current_user), class: 'nav-link text-light' do %>
                <i class="fas fa-home"></i> Home
              <% end %>
            </li>
            <li>
              <%= link_to users_path, class: 'nav-link text-light' do %>
                <i class="fas fa-users"></i> Users
              <% end %>
            </li>
            <li>
              <%= link_to books_path, class: 'nav-link text-light' do %>
                <i class="fas fa-book-open"></i> Books
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                <i class="fas fa-sign-out-alt"></i> Log out
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to root_path, class: 'nav-link text-light' do %>
                <i class="fas fa-home"></i> Home
              <% end %>
            </li>
            <li>
              <%= link_to about_path, class: 'nav-link text-light' do %>
                <i class="fas fa-link"></i> About
              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                <i class="fas fa-user-plus"></i> Sing up
              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
                <i class="fas fa-sign-in-alt"></i> Log in
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>
<%= yield %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/users/_user_info.html.erb
<%= image_tag user.get_profile_image(100,100) %>
  <table>
    <tbody>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
    </tbody>
  </table>
  <div class="button-item mt-1">
    <% if user == current_user %>
      <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
    <% end %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container pt-3">
  <div class="row">
    <div class="mx-auto">
    <h2>User info</h2>
      <%= form_with model:@user do |f| %>
      
      <table>
        <label for="inputName">Name</label></br>
        <%= f.text_field :name, autofocus: true, id:"inputName" %></br>
        
        <label for="inputImage">Image</label></br>
        <%= f.file_field :profile_image,  accept: "image/*" %></br>
        
        <label for="inputIntroduction">Introduction</label></br>
        <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction" %></br>
        
        <div class-"book-botton">
          <input class="btn btn-secondary" type="submit" value="Update User">
        </div>
      <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5">
  <div class="row">
    <div class="col-md-3">
      <h2 class="mt-3">User info</h2>
        <%= render 'user_info', user: @user %>
      
      <h2 class="mt-3">New Book</h2>
        <%= render 'books/new_book', book: @book %>
    </div>
    
    <div class="col-md-8 offset-md-1">
      <h2 class="mt-3">Users</h2>
      <table class="table">
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
        <% @users.each do |user| %>
        <tr>
          <td><%= image_tag user.get_profile_image(100,100) %></td>
          <td><%= user.name %></td>
          <td><%= link_to 'Show', user_path(user) %></td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-3">
  <div class="row">
    <div class="col-md-3">
      <h2 class="mt-3">User info</h2>
        <%= render 'user_info', user: @user %>
      
      <h2 class="mt-3">New Book</h2>
        <%= render 'books/new_book', book: @book %>
    </div>
    
    <div class="col-md-8 offset-md-1">
      <h2 class="mt-3">Books</h2>
      <table class="table">
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
        
        <% @books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(@user) do %>
              <%= image_tag @user.get_profile_image(50,50) %>
            <% end %>
          </td>
          <td>
            <%= link_to book.title, book_path(book) %>
          </td>
          <td>
            <%= book.body %>
          </td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>